/**
 * AUTO-GENERATED BUILD CONFIGURATION
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file is generated at build time by scripts/generate-config.ts
 * Generated at: 2026-03-12T20:28:43.579Z
 * 
 * To modify these values:
 *   - Local development: Edit .env file and run 'deno task dev'
 *   - Production build: Set environment variables in CI/CD and run build script
 */

export const BUILD_CONFIG = {
  oauth: {
    domain: "funky-pegasus-93.clerk.accounts.dev",
    clientId: "9AwGVidNiAijmSF2",
    type: "clerk",
    redirectUri: "http://localhost:8918/callback",
    scopes: [
      "profile",
      "email",
      "openid"
    ],
  },
  api: {
    endpoint: "http://localhost:8080",
    dashboardUrl: "https://localhost:3000",
  },
} as const;

// Build metadata (for debugging)
export const BUILD_METADATA = {
  timestamp: "2026-03-12T20:28:43.579Z",
  generator: "scripts/generate-config.ts",
} as const;
