#!/usr/bin/env -S deno run --allow-env --allow-read --allow-write

/**
 * Configuration Generator Script
 * 
 * Reads environment variables and generates a static TypeScript config file
 * for compilation into binaries. This ensures that compiled binaries have
 * hardcoded configuration values that cannot be changed at runtime.
 * 
 * Usage:
 *   deno task config:gen              # Generate from current environment
 *   deno task config:gen:local        # Generate from .env file
 *   
 * Required Environment Variables:
 *   - VERSION
 *   - API_ENDPOINT
 */

const REQUIRED_VARS = [
  "VERSION",
  "API_ENDPOINT",
];

// Read and validate environment variables
const config: Record<string, string> = {};
const missingVars: string[] = [];

for (const varName of REQUIRED_VARS) {
  const value = Deno.env.get(varName);
  if (!value) {
    missingVars.push(varName);
  } else {
    config[varName] = value;
  }
}

if (missingVars.length > 0) {
  console.error("❌ Error: Missing required environment variables:");
  for (const varName of missingVars) {
    console.error(`  - ${varName}`);
  }
  console.error("\nPlease set these variables in your environment or .env file.");
  console.error("\nExample .env file:");
  console.error(`
VERSION=0.1.0
API_ENDPOINT=http://localhost:8080
  `);
  Deno.exit(1);
}

// Generate the TypeScript configuration file
const buildTimestamp = new Date().toISOString();

const configFileContent = `import type { AppConfig } from "./types.ts";

/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/gen_config.ts
 * Generated at: ${buildTimestamp}
 * 
 * This file contains hardcoded configuration values for compiled binaries.
 * Values are captured from environment variables at build time.
 */

export const VERSION = "${config.VERSION}";

export const CONFIG: AppConfig = {
  api: {
    endpoint: "${config.API_ENDPOINT}",
  },
} as const;
`;

// Write the generated configuration file
const outputPath = "./packages/core/config/generated.ts";
await Deno.writeTextFile(outputPath, configFileContent);

console.log("✓ Generated build configuration:");
console.log(`  Output: ${outputPath}`);
console.log(`  Version: ${config.VERSION}`);
console.log(`  API Endpoint: ${config.API_ENDPOINT}`);
console.log(`  Build Timestamp: ${buildTimestamp}`);
console.log("\n✓ Config is ready for compilation");
