#!/usr/bin/env -S deno run --allow-env --allow-read --allow-write

/**
 * Configuration Generator Script
 * 
 * Reads environment variables and generates a static TypeScript config file
 * for compilation into binaries. This ensures that compiled binaries have
 * hardcoded configuration values that cannot be changed at runtime.
 * 
 * Usage:
 *   deno task config:gen              # Generate from current environment
 *   deno task config:gen:local        # Generate from .env file
 *   
 * Required Environment Variables:
 *   - VERSION
 *   - OAUTH_DOMAIN
 *   - OAUTH_CLIENT_ID
 *   - OAUTH_TYPE
 *   - OAUTH_REDIRECT_URI
 *   - OAUTH_SCOPES
 *   - API_ENDPOINT
 *   - DASHBOARD_URL
 */

const REQUIRED_VARS = [
  "VERSION",
  "OAUTH_DOMAIN",
  "OAUTH_CLIENT_ID",
  "OAUTH_TYPE",
  "OAUTH_REDIRECT_URI",
  "OAUTH_SCOPES",
  "API_ENDPOINT",
  "DASHBOARD_URL",
];

// Read and validate environment variables
const config: Record<string, string> = {};
const missingVars: string[] = [];

for (const varName of REQUIRED_VARS) {
  const value = Deno.env.get(varName);
  if (!value) {
    missingVars.push(varName);
  } else {
    config[varName] = value;
  }
}

if (missingVars.length > 0) {
  console.error("❌ Error: Missing required environment variables:");
  for (const varName of missingVars) {
    console.error(`  - ${varName}`);
  }
  console.error("\nPlease set these variables in your environment or .env file.");
  console.error("\nExample .env file:");
  console.error(`
VERSION=0.1.0
OAUTH_DOMAIN=your-app.clerk.accounts.dev
OAUTH_CLIENT_ID=your_client_id
OAUTH_TYPE=clerk
OAUTH_REDIRECT_URI=http://localhost:8918/callback
OAUTH_SCOPES=profile email openid
API_ENDPOINT=http://localhost:8080
DASHBOARD_URL=http://localhost:3000
  `);
  Deno.exit(1);
}

// Parse scopes
const scopesArray = config.OAUTH_SCOPES.split(" ").map(s => s.trim()).filter(Boolean);
const scopesFormatted = JSON.stringify(scopesArray, null, 4).replace(/\n/g, "\n    ");

// Generate the TypeScript configuration file
const buildTimestamp = new Date().toISOString();

const configFileContent = `import type { AppConfig } from "./types.ts";

/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/gen_config.ts
 * Generated at: ${buildTimestamp}
 * 
 * This file contains hardcoded configuration values for compiled binaries.
 * Values are captured from environment variables at build time.
 */

export const VERSION = "${config.VERSION}";

export const CONFIG: AppConfig = {
  oauth: {
    domain: "${config.OAUTH_DOMAIN}",
    clientId: "${config.OAUTH_CLIENT_ID}",
    type: "${config.OAUTH_TYPE}" as const,
    redirectUri: "${config.OAUTH_REDIRECT_URI}",
    scopes: ${scopesFormatted},
  },
  api: {
    endpoint: "${config.API_ENDPOINT}",
    dashboardUrl: "${config.DASHBOARD_URL}",
  },
} as const;
`;

// Write the generated configuration file
const outputPath = "./packages/core/config/generated.ts";
await Deno.writeTextFile(outputPath, configFileContent);

console.log("✓ Generated build configuration:");
console.log(`  Output: ${outputPath}`);
console.log(`  Version: ${config.VERSION}`);
console.log(`  OAuth Domain: ${config.OAUTH_DOMAIN}`);
console.log(`  OAuth Client ID: ${config.OAUTH_CLIENT_ID}`);
console.log(`  API Endpoint: ${config.API_ENDPOINT}`);
console.log(`  Dashboard URL: ${config.DASHBOARD_URL}`);
console.log(`  Build Timestamp: ${buildTimestamp}`);
console.log("\n✓ Config is ready for compilation");
