#!/usr/bin/env -S deno run --allow-env --allow-read --allow-write

/**
 * Build Configuration Generator
 * 
 * This script generates a static TypeScript configuration file with hardcoded
 * environment variable values. This ensures that when the binary is compiled,
 * the configuration is truly baked in and cannot be changed at runtime.
 * 
 * Usage:
 *   - Local development: Reads from .env file (via Deno.env after load)
 *   - CI/CD: Reads from environment variables set by CI/CD provider
 * 
 * Required Environment Variables:
 *   - OAUTH_DOMAIN
 *   - OAUTH_CLIENT_ID
 *   - OAUTH_TYPE
 *   - OAUTH_REDIRECT_URI
 *   - OAUTH_SCOPES
 *   - API_ENDPOINT
 *   - DASHBOARD_URL
 */

import { load } from "jsr:@std/dotenv";

// Load .env file if it exists (for local development)
// In CI/CD, environment variables will already be set
await load({ export: true, envPath: ".env" });

interface EnvironmentConfig {
  OAUTH_DOMAIN: string;
  OAUTH_CLIENT_ID: string;
  OAUTH_TYPE: string;
  OAUTH_REDIRECT_URI: string;
  OAUTH_SCOPES: string;
  API_ENDPOINT: string;
  DASHBOARD_URL: string;
}

const REQUIRED_VARS: (keyof EnvironmentConfig)[] = [
  "OAUTH_DOMAIN",
  "OAUTH_CLIENT_ID",
  "OAUTH_TYPE",
  "OAUTH_REDIRECT_URI",
  "OAUTH_SCOPES",
  "API_ENDPOINT",
  "DASHBOARD_URL",
];

// Read and validate environment variables
const config: Partial<EnvironmentConfig> = {};
const missingVars: string[] = [];

for (const varName of REQUIRED_VARS) {
  const value = Deno.env.get(varName);
  if (!value) {
    missingVars.push(varName);
  } else {
    config[varName] = value;
  }
}

if (missingVars.length > 0) {
  console.error("❌ Error: Missing required environment variables:");
  for (const varName of missingVars) {
    console.error(`  - ${varName}`);
  }
  console.error("\nPlease set these variables in your .env file or environment.");
  console.error("\nFor local development, copy .env.template to .env and fill in the values.");
  console.error("For CI/CD, set these as secrets/environment variables in your CI/CD provider.");
  Deno.exit(1);
}

// Generate the TypeScript configuration file
const buildTimestamp = new Date().toISOString();
const scopesArray = (config.OAUTH_SCOPES || "").split(" ").map(s => s.trim()).filter(Boolean);

// Format scopes array with proper indentation
const scopesFormatted = JSON.stringify(scopesArray, null, 2).split('\n').map((line, idx) => {
  if (idx === 0) return line;
  return '    ' + line;
}).join('\n');

const configFileContent = `/**
 * AUTO-GENERATED BUILD CONFIGURATION
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file is generated at build time by scripts/generate-config.ts
 * Generated at: ${buildTimestamp}
 * 
 * To modify these values:
 *   - Local development: Edit .env file and run 'deno task dev'
 *   - Production build: Set environment variables in CI/CD and run build script
 */

export const BUILD_CONFIG = {
  oauth: {
    domain: "${config.OAUTH_DOMAIN}",
    clientId: "${config.OAUTH_CLIENT_ID}",
    type: "${config.OAUTH_TYPE}",
    redirectUri: "${config.OAUTH_REDIRECT_URI}",
    scopes: ${scopesFormatted},
  },
  api: {
    endpoint: "${config.API_ENDPOINT}",
    dashboardUrl: "${config.DASHBOARD_URL}",
  },
} as const;

// Build metadata (for debugging)
export const BUILD_METADATA = {
  timestamp: "${buildTimestamp}",
  generator: "scripts/generate-config.ts",
} as const;
`;

// Write the generated configuration file
const outputPath = "./src/config/build-config.ts";
await Deno.writeTextFile(outputPath, configFileContent);

console.log("✓ Generated build configuration:");
console.log(`  Output: ${outputPath}`);
console.log(`  OAuth Domain: ${config.OAUTH_DOMAIN}`);
console.log(`  OAuth Client ID: ${config.OAUTH_CLIENT_ID}`);
console.log(`  API Endpoint: ${config.API_ENDPOINT}`);
console.log(`  Dashboard URL: ${config.DASHBOARD_URL}`);
console.log(`  Build Timestamp: ${buildTimestamp}`);
